import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#EBF3FA",
        foreground: "#0F172A",
        surface: "#FFFFFF",
        "surface-dim": "#E2ECF6",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F1F6FB",
        "surface-container": "#FFFFFF",
        "surface-container-high": "#E8F1F9",
        "surface-container-highest": "#DFEAF4",
        "surface-variant": "#E0ECF8",
        "on-surface": "#0F172A",
        "on-surface-variant": "#475569",
        "inverse-surface": "#0F172A",
        "inverse-on-surface": "#F8FAFC",
        outline: "#94B8D7",
        "outline-variant": "#CBDCEB",
        "surface-tint": "#0284C7",
        primary: "#0284C7",
        "on-primary": "#FFFFFF",
        "primary-container": "#E0F2FE",
        "on-primary-container": "#0369A1",
        "primary-fixed": "#E0F2FE",
        "primary-fixed-dim": "#BAE6FD",
        "on-primary-fixed": "#0C4A6E",
        "on-primary-fixed-variant": "#0369A1",
        "inverse-primary": "#38BDF8",
        secondary: "#475569",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#F1F5F9",
        "on-secondary-container": "#1E293B",
        "secondary-fixed": "#E2E8F0",
        "secondary-fixed-dim": "#CBD5E1",
        "on-secondary-fixed": "#0F172A",
        "on-secondary-fixed-variant": "#334155",
        tertiary: "#0369A1",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#E0F2FE",
        "on-tertiary-container": "#075985",
        "tertiary-fixed": "#E0F2FE",
        "tertiary-fixed-dim": "#BAE6FD",
        "on-tertiary-fixed": "#0C4A6E",
        "on-tertiary-fixed-variant": "#0369A1",
        error: "#DC2626",
        "on-error": "#FFFFFF",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",
        "on-background": "#0F172A",
        tactical: {
          bg: "#EBF3FA",
          panel: "#FFFFFF",
          panelHeader: "#F0F6FC",
          card: "#FFFFFF",
          cardHover: "#F8FBFE",
          border: "#CBDCEB",
          borderBright: "#0284C7",
          accent: "#0284C7",
          primary: "#0284C7",
          cyan: "#0EA5E9",
          red: "#DC2626",
          amber: "#D97706",
          green: "#16A34A",
          blue: "#0284C7",
          lightBlue: "#E0F2FE",
          iceBlue: "#BAE6FD",
          sky: "#38BDF8",
          muted: "#64748B",
          text: "#0F172A",
          textMuted: "#475569",
        },
      },
      fontFamily: {
        "display-2xl": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "headline-md-mobile": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        sans: ["Inter", "Geist", "sans-serif"],
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-2xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      spacing: {
        unit: "4px",
        gutter: "1px",
        "stack-sm": "12px",
        "stack-md": "32px",
        "stack-lg": "80px",
        "margin-page": "64px",
        "margin-mobile": "24px",
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      animation: {
        "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
