import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c5c7c1",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#8f918c",
        "outline-variant": "#454843",
        "surface-tint": "#c6c7c2",
        primary: "#ffffff",
        "on-primary": "#121212",
        "primary-container": "#e3e3de",
        "on-primary-container": "#636561",
        "primary-fixed": "#e3e3de",
        "primary-fixed-dim": "#c6c7c2",
        "on-primary-fixed": "#1a1c19",
        "on-primary-fixed-variant": "#454744",
        "inverse-primary": "#5d5f5b",
        secondary: "#c8c6c6",
        "on-secondary": "#303030",
        "secondary-container": "#494949",
        "on-secondary-container": "#b9b8b8",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c8c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        tertiary: "#ffffff",
        "on-tertiary": "#352f30",
        "tertiary-container": "#ebe0e1",
        "on-tertiary-container": "#6a6364",
        "tertiary-fixed": "#ebe0e1",
        "tertiary-fixed-dim": "#cec4c5",
        "on-tertiary-fixed": "#1f1a1b",
        "on-tertiary-fixed-variant": "#4c4546",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        // Legacy tactical mapped to clean obsidian shades
        tactical: {
          bg: "#131313",
          panel: "#1c1b1b",
          card: "#201f1f",
          cardHover: "#2a2a2a",
          border: "#454843",
          borderBright: "#8f918c",
          accent: "#ffffff",
          primary: "#ffffff",
          cyan: "#e5e2e1",
          red: "#ffb4ab",
          amber: "#e4e2e2",
          green: "#c6c7c2",
          blue: "#c8c6c6",
          purple: "#ebe0e1",
          muted: "#8f918c",
          text: "#e5e2e1",
          textMuted: "#c5c7c1",
        },
      },
      fontFamily: {
        "display-2xl": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "headline-md-mobile": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        sans: ["Inter", "Geist", "sans-serif"],
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-2xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      spacing: {
        unit: "4px",
        gutter: "1px",
        "stack-sm": "12px",
        "stack-md": "32px",
        "stack-lg": "80px",
        "margin-page": "64px",
        "margin-mobile": "24px",
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      animation: {
        "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
